services:
  - type: web
    name: bengal-election
    runtime: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: ECI_RESULTS_URL
        value: https://results.eci.gov.in/ResultAcGenMay2026/partywiseresult-S25.htm
